/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    colors:{
      'brown':'#d87d4a',
      'light-brown':'#fbaf85',
      'black':'#000000',
      'light-black':'#101010',
      'gray':'#f1f1f1',
      'light-gray':'#fafafa',
      'white':'#ffffff',
    },

    extend: {
      backgroundImage:{
        'mobile-hero-image': "url('/assets/home/mobile/image-header.jpg')",
        'tablet-hero-image': "url('/assets/home/tablet/image-header.jpg')",
        'desktop-hero-image': "url('/assets/home/desktop/image-hero.jpg')",
        'desktop-zx7': "url('/assets/home/desktop/image-speaker-zx7.jpg')",
        'tablet-zx7': "url('/assets/home/tablet/image-speaker-zx7.jpg')",
        'mobile-zx7': "url('/assets/home/mobile/image-speaker-zx7.jpg')",
        'desktop-yx1': "url('/assets/home/desktop/image-earphones-yx1.jpg')",
        'tablet-yx1': "url('/assets/home/tablet/image-earphones-yx1.jpg')",
        'mobile-yx1': "url('/assets/home/mobile/image-earphones-yx1.jpg')",
        'desktop-best-gear': "url('/assets/shared/desktop/image-best-gear.jpg')",
        'tablet-best-gear': "url('/assets/shared/tablet/image-best-gear.jpg')",
        'mobile-best-gear': "url('/assets/shared/mobile/image-best-gear.jpg')",
        'desktop-xx99markII': "url('/assets/product-xx99-mark-two-headphones/desktop/image-category-page-preview.jpg')",
        'tablet-xx99markII': "url('/assets/product-xx99-mark-two-headphones/tablet/image-category-page-preview.jpg')",
        'mobile-xx99markII': "url('/assets/product-xx99-mark-two-headphones/mobile/image-category-page-preview.jpg')",
        'desktop-xx99markII-gallery-1': "url('/assets/product-xx99-mark-two-headphones/desktop/image-gallery-1.jpg')",
        'tablet-xx99markII-gallery-1': "url('/assets/product-xx99-mark-two-headphones/tablet/image-gallery-1.jpg')",
        'mobile-xx99markII-gallery-1': "url('/assets/product-xx99-mark-two-headphones/mobile/image-gallery-1.jpg')",
        'desktop-xx99markII-gallery-2': "url('/assets/product-xx99-mark-two-headphones/desktop/image-gallery-2.jpg')",
        'tablet-xx99markII-gallery-2': "url('/assets/product-xx99-mark-two-headphones/tablet/image-gallery-2.jpg')",
        'mobile-xx99markII-gallery-2': "url('/assets/product-xx99-mark-two-headphones/mobile/image-gallery-2.jpg')",
        'desktop-xx99markII-gallery-3': "url('/assets/product-xx99-mark-two-headphones/desktop/image-gallery-3.jpg')",
        'tablet-xx99markII-gallery-3': "url('/assets/product-xx99-mark-two-headphones/tablet/image-gallery-3.jpg')",
        'mobile-xx99markII-gallery-3': "url('/assets/product-xx99-mark-two-headphones/mobile/image-gallery-3.jpg')",
        'desktop-xx99markI-gallery-1': "url('/assets/product-xx99-mark-one-headphones/desktop/image-gallery-1.jpg')",
        'tablet-xx99markI-gallery-1': "url('/assets/product-xx99-mark-one-headphones/tablet/image-gallery-1.jpg')",
        'mobile-xx99markI-gallery-1': "url('/assets/product-xx99-mark-one-headphones/mobile/image-gallery-1.jpg')",
        'desktop-xx99markI-gallery-2': "url('/assets/product-xx99-mark-one-headphones/desktop/image-gallery-2.jpg')",
        'tablet-xx99markI-gallery-2': "url('/assets/product-xx99-mark-one-headphones/tablet/image-gallery-2.jpg')",
        'mobile-xx99markI-gallery-2': "url('/assets/product-xx99-mark-one-headphones/mobile/image-gallery-2.jpg')",
        'desktop-xx99markI-gallery-3': "url('/assets/product-xx99-mark-one-headphones/desktop/image-gallery-3.jpg')",
        'tablet-xx99markI-gallery-3': "url('/assets/product-xx99-mark-one-headphones/tablet/image-gallery-3.jpg')",
        'mobile-xx99markI-gallery-3': "url('/assets/product-xx99-mark-one-headphones/mobile/image-gallery-3.jpg')",
        'desktop-xx59-gallery-1': "url('/assets/product-xx59-headphones/desktop/image-gallery-1.jpg')",
        'tablet-xx59-gallery-1': "url('/assets/product-xx59-headphones/tablet/image-gallery-1.jpg')",
        'mobile-xx59-gallery-1': "url('/assets/product-xx59-headphones/mobile/image-gallery-1.jpg')",
        'desktop-xx59-gallery-2': "url('/assets/product-xx59-headphones/desktop/image-gallery-2.jpg')",
        'tablet-xx59-gallery-2': "url('/assets/product-xx59-headphones/tablet/image-gallery-2.jpg')",
        'mobile-xx59-gallery-2': "url('/assets/product-xx59-headphones/mobile/image-gallery-2.jpg')",
        'desktop-xx59-gallery-3': "url('/assets/product-xx59-headphones/desktop/image-gallery-3.jpg')",
        'tablet-xx59-gallery-3': "url('/assets/product-xx59-headphones/tablet/image-gallery-3.jpg')",
        'mobile-xx59-gallery-3': "url('/assets/product-xx59-headphones/mobile/image-gallery-3.jpg')",
        'desktop-zx9-gallery-1': "url('/assets/product-zx9-speaker/desktop/image-gallery-1.jpg')",
        'tablet-zx9-gallery-1': "url('/assets/product-zx9-speaker/tablet/image-gallery-1.jpg')",
        'mobile-zx9-gallery-1': "url('/assets/product-zx9-speaker/mobile/image-gallery-1.jpg')",
        'desktop-zx9-gallery-2': "url('/assets/product-zx9-speaker/desktop/image-gallery-2.jpg')",
        'tablet-zx9-gallery-2': "url('/assets/product-zx9-speaker/tablet/image-gallery-2.jpg')",
        'mobile-zx9-gallery-2': "url('/assets/product-zx9-speaker/mobile/image-gallery-2.jpg')",
        'desktop-zx9-gallery-3': "url('/assets/product-zx9-speaker/desktop/image-gallery-3.jpg')",
        'tablet-zx9-gallery-3': "url('/assets/product-zx9-speaker/tablet/image-gallery-3.jpg')",
        'mobile-zx9-gallery-3': "url('/assets/product-zx9-speaker/mobile/image-gallery-3.jpg')",
        'desktop-zx7-gallery-1': "url('/assets/product-zx7-speaker/desktop/image-gallery-1.jpg')",
        'tablet-zx7-gallery-1': "url('/assets/product-zx7-speaker/tablet/image-gallery-1.jpg')",
        'mobile-zx7-gallery-1': "url('/assets/product-zx7-speaker/mobile/image-gallery-1.jpg')",
        'desktop-zx7-gallery-2': "url('/assets/product-zx7-speaker/desktop/image-gallery-2.jpg')",
        'tablet-zx7-gallery-2': "url('/assets/product-zx7-speaker/tablet/image-gallery-2.jpg')",
        'mobile-zx7-gallery-2': "url('/assets/product-zx7-speaker/mobile/image-gallery-2.jpg')",
        'desktop-zx7-gallery-3': "url('/assets/product-zx7-speaker/desktop/image-gallery-3.jpg')",
        'tablet-zx7-gallery-3': "url('/assets/product-zx7-speaker/tablet/image-gallery-3.jpg')",
        'mobile-zx7-gallery-3': "url('/assets/product-zx7-speaker/mobile/image-gallery-3.jpg')",
        'desktop-yx1-gallery-1': "url('/assets/product-yx1-earphones/desktop/image-gallery-1.jpg')",
        'tablet-yx1-gallery-1': "url('/assets/product-yx1-earphones/tablet/image-gallery-1.jpg')",
        'mobile-yx1-gallery-1': "url('/assets/product-yx1-earphones/mobile/image-gallery-1.jpg')",
        'desktop-yx1-gallery-2': "url('/assets/product-yx1-earphones/desktop/image-gallery-2.jpg')",
        'tablet-yx1-gallery-2': "url('/assets/product-yx1-earphones/tablet/image-gallery-2.jpg')",
        'mobile-yx1-gallery-2': "url('/assets/product-yx1-earphones/mobile/image-gallery-2.jpg')",
        'desktop-yx1-gallery-3': "url('/assets/product-yx1-earphones/desktop/image-gallery-3.jpg')",
        'tablet-yx1-gallery-3': "url('/assets/product-yx1-earphones/tablet/image-gallery-3.jpg')",
        'mobile-yx1-gallery-3': "url('/assets/product-yx1-earphones/mobile/image-gallery-3.jpg')",
        'desktop-xx99markI': "url('/assets/product-xx99-mark-one-headphones/desktop/image-category-page-preview.jpg')",
        'tablet-xx99markI': "url('/assets/product-xx99-mark-one-headphones/tablet/image-category-page-preview.jpg')",
        'mobile-xx99markI': "url('/assets/product-xx99-mark-one-headphones/mobile/image-category-page-preview.jpg')",
        'desktop-xx99markI-product': "url('/assets/product-xx99-mark-one-headphones/desktop/image-product.jpg')",
        'tablet-xx99markI-product': "url('/assets/product-xx99-mark-one-headphones/tablet/image-product.jpg')",
        'mobile-xx99markI-product': "url('/assets/product-xx99-mark-one-headphones/mobile/image-product.jpg')",
        'desktop-xx99markII-product': "url('/assets/product-xx99-mark-two-headphones/desktop/image-product.jpg')",
        'tablet-xx99markII-product': "url('/assets/product-xx99-mark-two-headphones/tablet/image-product.jpg')",
        'mobile-xx99markII-product': "url('/assets/product-xx99-mark-two-headphones/mobile/image-product.jpg')",
        'desktop-xx59': "url('/assets/product-xx59-headphones/desktop/image-category-page-preview.jpg')",
        'tablet-xx59': "url('/assets/product-xx59-headphones/tablet/image-category-page-preview.jpg')",
        'mobile-xx59': "url('/assets/product-xx59-headphones/mobile/image-category-page-preview.jpg')",
        'desktop-xx59-product': "url('/assets/product-xx59-headphones/desktop/image-product.jpg')",
        'tablet-xx59-product': "url('/assets/product-xx59-headphones/tablet/image-product.jpg')",
        'mobile-xx59-product': "url('/assets/product-xx59-headphones/mobile/image-product.jpg')",
        'desktop-zx9': "url('/assets/product-zx9-speaker/desktop/image-category-page-preview.jpg')",
        'tablet-zx9': "url('/assets/product-zx9-speaker/tablet/image-category-page-preview.jpg')",
        'mobile-zx9': "url('/assets/product-zx9-speaker/mobile/image-category-page-preview.jpg')",
        'desktop-zx9-product': "url('/assets/product-zx9-speaker/desktop/image-product.jpg')",
        'tablet-zx9-product': "url('/assets/product-zx9-speaker/tablet/image-product.jpg')",
        'mobile-zx9-product': "url('/assets/product-zx9-speaker/mobile/image-product.jpg')",
        'desktop-zx7-product': "url('/assets/product-zx7-speaker/desktop/image-product.jpg')",
        'tablet-zx7-product': "url('/assets/product-zx7-speaker/tablet/image-product.jpg')",
        'mobile-zx7-product': "url('/assets/product-zx7-speaker/mobile/image-product.jpg')",
        'desktop-zx7-speaker': "url('/assets/product-zx7-speaker/desktop/image-category-page-preview.jpg')",
        'tablet-zx7-speaker': "url('/assets/product-zx7-speaker/tablet/image-category-page-preview.jpg')",
        'mobile-zx7-speaker': "url('/assets/product-zx7-speaker/mobile/image-category-page-preview.jpg')",
        'desktop-yx1-earphones': "url('/assets/product-yx1-earphones/desktop/image-category-page-preview.jpg')",
        'tablet-yx1-earphones': "url('/assets/product-yx1-earphones/tablet/image-category-page-preview.jpg')",
        'mobile-yx1-earphones': "url('/assets/product-yx1-earphones/mobile/image-category-page-preview.jpg')",
      },
    },
    fontFamily:{
      Manrope:["Manrope", 'sans-serif']
    },
  },
  plugins: [],
}
